import json
import os

NOTEBOOK_PATH = "antigravity_horn_audit.ipynb"

# 1. Load the existing notebook
if not os.path.exists(NOTEBOOK_PATH):
    print(f"Error: {NOTEBOOK_PATH} not found.")
    exit(1)

with open(NOTEBOOK_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)

# 2. Prepare the markdown cell content
markdown_source = [
    "# 🔄 LangGraph & Google-GenAI SDK Multi-Turn Integration\n",
    "We successfully integrated a stateful, multi-turn orchestrator using the modern `google-genai` SDK inside a LangGraph workflow (`langgraph_gemini_test.py`).\n",
    "It maintains conversational history across turns and executes local repository inspection tools.\n",
    "\n",
    "#### 📜 Verified Integration Code:\n",
    "```python\n",
    "\"\"\"\n",
    "LangGraph & Google-GenAI SDK Integration Test\n",
    "===============================================\n",
    "A stateful, multi-turn orchestrator that runs the Gemini API via the modern\n",
    "google-genai SDK inside a LangGraph workflow. Exposes local repo inspection tools.\n",
    "\"\"\"\n",
    "import os\n",
    "import sys\n",
    "import asyncio\n",
    "from typing import Annotated, List, Literal, Dict, Any, Union\n",
    "import operator\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv()\n",
    "from google import genai\n",
    "from google.genai import types\n",
    "from langgraph.graph import StateGraph, START, END\n",
    "from typing_extensions import TypedDict\n",
    "\n",
    "def list_workspace_files() -> dict:\n",
    "    \"\"\"List all Python files in the current folder.\"\"\"\n",
    "    files = [f for f in os.listdir(\".\") if f.endswith(\".py\")]\n",
    "    return {\"status\": \"success\", \"files\": files}\n",
    "\n",
    "def view_file_preview(filename: str) -> dict:\n",
    "    \"\"\"Read the first 15 lines of a python file to inspect its code.\"\"\"\n",
    "    if not os.path.exists(filename):\n",
    "        return {\"status\": \"error\", \"message\": f\"File '{filename}' not found.\"}\n",
    "    try:\n",
    "        with open(filename, \"r\", encoding=\"utf-8\", errors=\"ignore\") as f:\n",
    "            lines = [f.readline() for _ in range(15)]\n",
    "        return {\"status\": \"success\", \"filename\": filename, \"preview\": \"\".join(lines)}\n",
    "    except Exception as e:\n",
    "        return {\"status\": \"error\", \"message\": str(e)}\n",
    "\n",
    "TOOLS_REGISTRY = {\n",
    "    \"list_workspace_files\": list_workspace_files,\n",
    "    \"view_file_preview\": view_file_preview,\n",
    "}\n",
    "\n",
    "class AgentState(TypedDict):\n",
    "    messages: Annotated[List[types.Content], operator.add]\n",
    "\n",
    "def normalize_messages(messages: List[Union[types.Content, dict, Any]]) -> List[types.Content]:\n",
    "    normalized = []\n",
    "    for msg in messages:\n",
    "        if isinstance(msg, types.Content):\n",
    "            normalized.append(msg)\n",
    "        elif isinstance(msg, dict):\n",
    "            role = msg.get(\"role\", \"user\")\n",
    "            if role == \"assistant\": role = \"model\"\n",
    "            normalized.append(types.Content(\n",
    "                role=role,\n",
    "                parts=[types.Part.from_text(text=msg.get(\"content\", \"\"))]\n",
    "            ))\n",
    "    return normalized\n",
    "\n",
    "async def call_gemini_agent(state: AgentState) -> dict:\n",
    "    client = genai.Client()\n",
    "    contents = normalize_messages(state[\"messages\"])\n",
    "    config = types.GenerateContentConfig(\n",
    "        system_instruction=\"You are the LangGraph-Gemini Bridge. Inspect the local codebase.\",\n",
    "        temperature=0.0,\n",
    "        tools=[list_workspace_files, view_file_preview]\n",
    "    )\n",
    "    response = client.models.generate_content(\n",
    "        model=\"gemini-2.5-flash\",\n",
    "        contents=contents,\n",
    "        config=config\n",
    "    )\n",
    "    model_content = response.candidates[0].content\n",
    "    if not model_content.role: model_content.role = \"model\"\n",
    "    return {\"messages\": [model_content]}\n",
    "\n",
    "async def execute_tools(state: AgentState) -> dict:\n",
    "    last_message = state[\"messages\"][-1]\n",
    "    tool_responses = []\n",
    "    for part in last_message.parts:\n",
    "        if part.function_call:\n",
    "            call = part.function_call\n",
    "            tool_func = TOOLS_REGISTRY.get(call.name)\n",
    "            result = tool_func(**call.args) if tool_func else {\"status\": \"error\"}\n",
    "            tool_responses.append(types.Part.from_function_response(\n",
    "                name=call.name, response={\"result\": result}\n",
    "            ))\n",
    "    return {\"messages\": [types.Content(role=\"user\", parts=tool_responses)]}\n",
    "\n",
    "def should_continue(state: AgentState) -> Literal[\"tools\", \"end\"]:\n",
    "    last_message = state[\"messages\"][-1]\n",
    "    if last_message.parts and any(p.function_call for p in last_message.parts):\n",
    "        return \"tools\"\n",
    "    return \"end\"\n",
    "\n",
    "def build_workflow() -> StateGraph:\n",
    "    workflow = StateGraph(AgentState)\n",
    "    workflow.add_node(\"agent\", call_gemini_agent)\n",
    "    workflow.add_node(\"tools\", execute_tools)\n",
    "    workflow.set_entry_point(\"agent\")\n",
    "    workflow.add_conditional_edges(\"agent\", should_continue, {\"tools\": \"tools\", \"end\": END})\n",
    "    workflow.add_edge(\"tools\", \"agent\")\n",
    "    return workflow.compile()\n",
    "```\n",
    "\n",
    "#### 📊 Verified Multi-Turn Execution Transcript:\n",
    "```text\n",
    "🚀 [START] Stateful LangGraph & google-genai Multi-Turn Test\n",
    "======================================================================\n",
    "\n",
    "👤 User (Turn 1): 'Please list the Python files in this folder.'\n",
    "\n",
    "🤖 Agent (Turn 1):\n",
    "Here are the Python files in this folder:\n",
    "\n",
    "*   `apply_fixes.py`\n",
    "*   `ask_antigravity.py`\n",
    "*   `ask_antigravity_code.py`\n",
    "*   `autonomous_search_clustering.py`\n",
    "*   `build_code_mining_notebook.py`\n",
    "*   `build_web_intel_notebook.py`\n",
    "*   `check_env.py`\n",
    "*   `check_lancedb.py`\n",
    "*   `check_sources.py`\n",
    "*   `chris_lake_fire_test.py`\n",
    "*   `code_lane_engine.py`\n",
    "*   `code_lane_steps.py`\n",
    "*   `code_lane_v2.py`\n",
    "*   `deep_scan.py`\n",
    "*   `deterministic_omni_pipeline.py`\n",
    "*   `export_chat.py`\n",
    "*   `find_chris_lake.py`\n",
    "*   `find_interferences.py`\n",
    "*   `forest_engine_cell.py`\n",
    "*   `github_audit.py`\n",
    "*   `langgraph_gemini_test.py`\n",
    "*   `main.py`\n",
    "*   `master_batch.py`\n",
    "*   `music_catelog.py`\n",
    "*   `patch_notebook.py`\n",
    "*   `pydantic_extractor.py`\n",
    "*   `rag_api.py`\n",
    "*   `run_data_dump.py`\n",
    "*   `sovereign_schemas.py`\n",
    "*   `spider_web_mapper.py`\n",
    "*   `spotify_probe.py`\n",
    "*   `test_ingest.py`\n",
    "*   `test_itunes.py`\n",
    "*   `update_nb.py`\n",
    "*   `vectorize_content.py`\n",
    "*   `web_scan.py`\n",
    "----------------------------------------------------------------------\n",
    "\n",
    "👤 User (Turn 2): 'Great. Can you show me the first 15 lines of update_nb.py?'\n",
    "\n",
    "🤖 Agent (Turn 2):\n",
    "Here's a preview of the first 15 lines of `update_nb.py`:\n",
    "\n",
    "```python\n",
    "import json\n",
    "import re\n",
    "\n",
    "with open('gemini_code_lane_cells.md', 'r', encoding='utf-8', errors='ignore') as f:\n",
    "    text = f.read()\n",
    "\n",
    "# find all cell objects\n",
    "# They look like { \"cell_type\": ... }\n",
    "cells = []\n",
    "matches = re.finditer(r'\\{\\s*\"cell_type\":\\s*\".*?\\}', text, re.DOTALL)\n",
    "# wait, regex for nested brackets is hard.\n",
    "# Let's just find the first { \"cell_type\" and the last } before ```\n",
    "start = text.find('{\\n \"cell_type\"')\n",
    "end = text.rfind('}')\n",
    "if start != -1 and end != -1:\n",
    "```\n",
    "======================================================================\n",
    "✅ [COMPLETE] Multi-Turn Workflow Execution Successful.\n",
    "```\n"
]

# 3. Prepare the dynamic code cell content
# This code defines the structured pre-flight check and runs a multi-turn LangGraph with it.
code_source = [
    "from google import genai\n",
    "from google.genai import types\n",
    "from pydantic import BaseModel, Field\n",
    "from typing import List\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "import asyncio\n",
    "\n",
    "load_dotenv()\n",
    "\n",
    "# ─── DYNAMIC SAFE PYDANTICS STRUCTURE: PRE-FLIGHT READINESS CHECK ───\n",
    "class OperationReadiness(BaseModel):\n",
    "    is_ready: bool = Field(\n",
    "        description=\"True if all required session features, database tables, and API environment configs are present to perform the requested operation.\"\n",
    "    )\n",
    "    missing_resources: List[str] = Field(\n",
    "        default_factory=list,\n",
    "        description=\"List of missing files, environment keys, table dependencies, or inputs needed before running.\"\n",
    "    )\n",
    "    remediation_steps: List[str] = Field(\n",
    "        default_factory=list,\n",
    "        description=\"Actionable steps the user or system must take to satisfy the schema constraints.\"\n",
    "    )\n",
    "\n",
    "def check_session_readiness(user_query: str, available_resources: list) -> OperationReadiness:\n",
    "    \"\"\"\n",
    "    Pre-flight validation using structured Gemini schema inference to check if the agent\n",
    "    is ready to execute or if it requires more input parameters.\n",
    "    \"\"\"\n",
    "    client = genai.Client()\n",
    "    \n",
    "    system_prompt = (\n",
    "        \"Analyze the user's intent and the available workspace/database resources. \"\n",
    "        \"Verify if the operation can be safely performed without missing context or raising errors. \"\n",
    "        \"Return the validated validation verdict using the OperationReadiness schema.\"\n",
    "    )\n",
    "    \n",
    "    user_prompt = f\"\"\"\n",
    "    User Intent: {user_query}\n",
    "    Available Files/Resources: {available_resources}\n",
    "    API Key Setup: {'GEMINI_API_KEY present' if os.environ.get('GEMINI_API_KEY') else 'GEMINI_API_KEY MISSING'}\n",
    "    \"\"\"\n",
    "    \n",
    "    response = client.models.generate_content(\n",
    "        model=\"gemini-2.5-flash\",\n",
    "        contents=user_prompt,\n",
    "        config=types.GenerateContentConfig(\n",
    "            system_instruction=system_prompt,\n",
    "            response_mime_type=\"application/json\",\n",
    "            response_schema=OperationReadiness,\n",
    "            temperature=0.0\n",
    "        )\n",
    "    )\n",
    "    \n",
    "    # Load and return the validated pydantic object\n",
    "    return OperationReadiness.model_validate_json(response.text)\n",
    "\n",
    "# ─── EXECUTE AN INTERACTIVE TEST ───\n",
    "query = \"Analyze the sonic profile of the audio files in /raw_sessions folder and check BPM alignments.\"\n",
    "available = [\"langgraph_gemini_test.py\", \"sovereign_schemas.py\", \"AI_Logs/\"]\n",
    "\n",
    "print(f\"🔍 Running Safe Pre-Flight Readiness Audit for query: '{query}'\")\n",
    "verdict = check_session_readiness(query, available)\n",
    "\n",
    "print(f\"\\nReady to operate? {'🟢 YES' if verdict.is_ready else '🔴 NO'}\")\n",
    "if not verdict.is_ready:\n",
    "    print(\"\\n⚠️ Missing dependencies/resources:\")\n",
    "    for resource in verdict.missing_resources:\n",
    "        print(f\"  - {resource}\")\n",
    "    print(\"\\n🛠️ Remediation Steps:\")\n",
    "    for step in verdict.remediation_steps:\n",
    "        print(f\"  - {step}\")\n"
]

# 4. Insert cells into notebook array
# Let's find if the markdown cell already exists, or just append them to the end of the cells list
markdown_cell = {
    "cell_type": "markdown",
    "id": "langgraph_integration_md",
    "metadata": {},
    "source": markdown_source
}

code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "dynamic_readiness_code",
    "metadata": {},
    "outputs": [],
    "source": code_source
}

# Append the new cells
nb["cells"].append(markdown_cell)
nb["cells"].append(code_cell)

# 5. Write the patched notebook back
with open(NOTEBOOK_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("Notebook successfully updated with Markdown documentation and Dynamic Readiness code cells.")
